lifter:
  subsystem: "lifter"
  description: "All motors used in the robot lifter mechanism live here for the lifter component"
  motors:
    groups: "motors" 
    winchMotor:
      channel: 40
      type: "SparkMax"
      inverted: False
      motorType: "kBrushless"
      pid: Null

description: "Base file stuff"